build:
  version: 2016-03-14 # version of the build schema.
  steps:
    main:
      name: marcosfelt/summit:latest
      dockerfile: Dockerfile.main
      secrets:
        id_rsa:
          type: file
          value: _env(HOME)/.ssh/docker_rsa
      cleanup:
        commands:
          - rm -rf /root/.ssh/
    in-silico:
      name: marcosfelt/summit:in-silico
      dockerfile: Dockerfile.in_silico
      depends_on:
        - main
  