[tool.poetry]
name = "summit"
version = "0.1.0"
description = "Tools for optimizing chemical reactions"
authors = ["Kobi Felton <kobi.c.f@gmail.com>"]
license = "MIT"
readme = 'README.md'
repository = "https://github.com/marcosfelt/summit"
homepage = "https://pypi.org/project/summit"
keywords = []

[tool.poetry.dependencies]
gpyopt = {git = "https://github.com/SheffieldML/GPyOpt.git"}
sklearn = "^0.0.0"
pandas = "^0.24.1"
matplotlib = "^3.0"
cheminventory="^0.2.1"
tqdm = "^4.31"
python = "^3.6"
panel = "^0.4.0"
holoviews = "^1.11"
pyDOE = "^0.3.8"

[tool.poetry.dev-dependencies]
black = {version = "^18.3-alpha.0",allows-prereleases = true}
jupyter = "^1.0"
jupyterlab = "^0.35.4"
bumpversion = "^0.5.3"
pylint = "^2.2"
pytest = "^3.0"
ipdb = "^0.12.0"
pytest-mock = "^1.10"

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
